dist: bionic
language: python
python:
  - "3.6"

services:
  #- neo4j
  - docker

before_install:
  - docker pull neo4j

install:
  - pip install -e .

script:
  - docker run -d -p7474:7474 -p7687:7687 --env=NEO4J_AUTH=none neo4j
  - python pedgraph/test/test.py
