dist: bionic
language: python
python:
  - "3.6"

services:
  - docker

env:
  - NEO4J_AUTH="none"

before_install:
  - docker pull neo4j

install:
  - pip install -e .

script:
  - docker run -d -p7474:7474 -p7687:7687 --env=NEO4J_AUTH=none neo4j
  - sleep 20  # Wait for neo4j database to start up.
  - python pedgraph/test/test.py
