dist: bionic
language: python
python:
  - "3.6"

services:
  #- neo4j
  #- docker

env:
  - NEO4J_VERSION="4.1.1"
  - NEO4J_AUTH="none"

before_install:
  #- docker pull neo4j

install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update && sudo apt-get install openjdk-8-jre-headless
  - curl -L http://dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz | tar xz
  - pip install -e .

script:
  #- docker run -d -p7474:7474 -p7687:7687 --env=NEO4J_AUTH=none neo4j
  - python pedgraph/test/test.py
