version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      # Primary container image where all commands run
      - image: olavurmortensen/pedgraph
        environment:
          NEO4J_URI: bolt://localhost:7687

      # Service container image available at `host: localhost`
      - image: neo4j
        entrypoint: /sbin/tini -g -s -- /docker-entrypoint.sh
        command: cd /var/lib/neo4j & neo4j
        environment:
          # No user/password needed to connect to DB.
          NEO4J_AUTH: none
    working_directory: /pedgraph
    steps:
      - run:
          command: python pedgraph/test/test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
