version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: olavurmortensen/pedgraph
    steps:
      - run:
          command: python pedgraph/test/test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
